### ISSUE TITLE
Cannot find anything with version 0.15

### ISSUE THREAD

**Issue by MartinSkold** [msmolkin/super-grep#1]
Hi!

This really solves a problem I been always bugged about. I you mentioning this tool in an hacker news thread. 

I installed version 0.15 with pip. However I am unable to find anything it. Either I don't understand the syntax or, don't give the right arguments, but if I stand in an folder containing `.cpp` and `.h` files, and run

```bash
    super-grep "./" "api_create" -d -1
```

Where `api_create` is a defined function in the file, it does not find it. I tried searching my notes for random words, but it cannot find any words with same command. For example 

```bash
    super-grep "~/Documents/Commonplace" "read" -d -1
```

I doesn't find the word. 

Am I doing something wrong? 

**Edit:** I am running on Ubuntu 22.04 with python version Python 3.10.13.

**Comment by msmolkin** [comment]
Hi Martin,

Thanks for checking out the tool. I'm sorry to hear that you're having trouble using it, and I appreciate your detailed report. I've taken a look at the issue, and I'm happy to report that I've hopefully fixed it in the latest version!

The problem you encountered was due to an incorrect handling of the depth argument when set to `-1` for infinite depth. I've addressed this issue in the latest version (0.1.8), and it should now work as expected.

To upgrade to the latest version, please run:

```
pip install --upgrade super-grep
```

After upgrading, please try running your commands again. I'm confident that you'll find the tool works as you expect now, although it may be a bit slow if the directory is large as it does go through all the files in all subdirectories per your command.

I would write the command this following way, but your way should work, too!

Input:
```
    super-grep . api_create -d -1
```

Output:
<img width="301" alt="Screenshot 2024-09-30 at 10 14 54 AM" src="https://github.com/user-attachments/assets/40e37057-60c7-4ec8-b4a3-828d47a0747e">


Let me know what you think!

**Comment by msmolkin** [comment]
Also just added file-type filtering for you that might improve performance by acting as a circuit breaker, so you can add the `-t` parameter to only search the source files themselves.

`super-grep . "ApiCreate" -H -s -C -t ".c,.h,.md" -d 2`

**Comment by MartinSkold** [comment]
Hi @msmolkin!

I missed the github notification, I get so many of them. But I saw this one. 

I just tested, and the search worked! I tried api_create, apiCreate and both those work well!

I will try to use it for a while, but for now, it looks like a search tool that will work perfectly for the code bases I use.
